import Head from "next/head";
import "bootstrap/dist/css/bootstrap.css";
import { useSession } from "next-auth/react";
import Carousel from "../components/Carousel";
import CardGroup from "../components/CardGroup";
export default function Home() {
  const { data: session, status } = useSession();

  if (status === "loading") {
    return <p>Loading...</p>;
  }
  return (
    <>
      <Head>
      <style>@import url('https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&display=swap');</style>
        <title>Enterprise Web Software Development</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Carousel />
      <CardGroup />
    </>
  );
}
